<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Tooltip Language Lines
    |--------------------------------------------------------------------------
    |
    */

    'ra2_file' => 'Para las Auditorías Ambientales e Informes Ambientales de Cumplimiento solo deberá adjuntar el oficio de aprobación. En el caso del informe de Cumplimiento de las Guías de Buenas Prácticas deberá adjuntar una declaración de su cumplimiento firmado por el Representante Legal.',
    'pa2_1_bool' => 'Se refiere a un número de medidas que pueden usar las empresas para mejorar su productividad, obtener ahorros de costos, y reducir el impacto ambiental de sus operaciones.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa cuenta con políticas/planes/estrategias  para promover el uso eficiente de materias primas, insumos y materiales en sus instalaciones?<br>- ¿La empresa aplica incentivos entre sus empleados y/o proveedores para fomentar el uso eficiente de materias primas, insumos y materiales?<br>- ¿Promueve campañas de sensibilización/concientización entre sus funcionarios para un uso más eficiente de materias primas, insumos y materiales?',
    'pa2_2_bool' => 'Es una estrategia de gestión productiva y ambiental que permite incrementar la eficiencia y la productividad de las empresas y reducir costos, al tiempo que minimiza los riesgos para la población humana y el medio ambiente.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa cuenta con políticas /planes/estrategias relacionadas a producción más limpia?<br>- ¿La empresa ha implementado alguna medida de producción más limpia recientemente o tiene pensado hacerlo en el próximo año?<br>- ¿La empresa promueve la compra y uso de materiales menos contaminantes en sus procesos?<br>- ¿La empresa ha invertido en tecnologías menos contaminantes o tiene pensado hacerlo en el próximo año?',
    'pa2_3_bool' => 'Implica prácticas de uso eficiente de la energía, con el fin de optimizar los procesos productivos y el empleo de la energía utilizando lo mismo o menos para producir más bienes y servicios.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa ha implementado alguna medida de eficiencia energética recientemente o tiene pensado hacerlo en el próximo año?<br>- ¿La empresa promueve el uso de energías alternativas en sus procesos y/o instalaciones?<br>- ¿La empresa invierte en nuevas tecnologías más eficientes?<br>- ¿Tiene alguna alianza con otras empresas públicas o privadas para promover la eficiencia energética interna?<br>- ¿Ha implementado acciones relacionadas al uso de iluminación LED o focos ahorradores en sus instalaciones?',
    'pa2_4_bool' => 'Implica la correcta gestión de los residuos sólidos (recojo, transporte, tratamiento, reciclaje y eliminación de los materiales de desecho).<br><strong>Preguntas de referencia</strong><br>- ¿La empresa fomenta el reciclaje y reuso de materiales utilizados entre sus funcionarios?<br>- ¿La empresa cuenta con políticas de reciclaje y reuso?<br>- ¿La empresa cuenta con basureros diferenciados para la disposición de residuos?<br>- ¿La empresa reduce la cantidad de empaques de sus productos o utiliza materiales reusables/reciclables en sus empaques?<br>- ¿La empresa participa en programas de voluntariado personal o corporativo para recuperar residuos en zonas específicas del cantón?<br>- ¿La empresa ofrece incentivos a las prácticas de reciclaje o a la separación de residuos dentro de sus instalaciones?',
    'pa2_5_bool' => 'Implica la correcta gestión de los recursos hídricos (captación, uso, consumo, tratamiento y disposición final).<br><strong>Preguntas de referencia</strong><br>- ¿La empresa ha instalado artefactos ahorradores en sus edificaciones o tiene pensado hacerlo en el próximo año?<br>- ¿Se promueve el uso eficiente del agua dentro de los procesos productivos y/o en el consumo de los empleados y clientes?<br>- ¿Se realizan campañas de concientización sobre la importancia del manejo adecuado de recursos hídricos?<br>- ¿Se realizan periódicamente actividades de mantenimiento en tuberías dañadas o antiguas dentro de las instalaciones de la empresa?<br>- ¿La empresa cuenta con procesos de cosecha de agua de lluvia?<br>- ¿La empresa cuenta con procesos de tratamiento de aguas residuales?',
    'pa2_6_bool' => 'Son modos de concebir el diseño arquitectónico de manera sustentable, buscando optimizar recursos naturales y sistemas de la edificación de tal modo que minimicen el impacto ambiental de los edificios sobre el medio ambiente y sus habitantes.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa implementa criterios de construcción sostenible en sus edificaciones y obras, en relación al uso del agua, suelo, energía y materiales?<br>- ¿La empresa implementa terrazas verdes, jardines verticales y/o huertos en sus instalaciones?<br>- ¿La empresa cuenta con infraestructura necesaria para captar y utilizar agua de lluvia y/o reutilizar aguas residuales?<br>- ¿La empresa reutiliza algunos materiales para nuevas construcciones? (Ej. ventanas, madera, puertas de construcciones antiguas que ya no se utilizan)',
    'pa2_7_bool' => 'Implica medidas en el sector de transporte para reducir las emisiones de gases de efecto invernadero.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa incentiva el uso de buses corporativos para el traslado de los trabajadores?<br>- ¿La empresa aplica un sistema de auto compartido?<br>- ¿La empresa fomenta el uso de bicicletas tanto dentro como fuera de las instalaciones (facilita parqueos para bicicletas y ciclovías dentro de las instalaciones)?<br>- ¿La empresa proporciona algún incentivo a sus empleados por desplazarse a pie o en transporte no motorizado  para llegar al trabajo?<br>- ¿La empresa fomenta el uso de videoconferencias entre los trabajadores?<br>- ¿La empresa promociona y facilita la sustitución de combustibles en vehículos de la empresa y de los trabajadores?<br>- ¿La empresa cuenta o se encuentra elaborando políticas que fomenten el transporte alternativo no motorizado?',
    'pa2_8_bool' => 'Son aquellas acciones asumidas por una empresa que pretenden reducir el impacto ambiental negativo que causan lo procesos productivos a través de cambios en la organización de los procesos y las actividades. <br><strong>Preguntas de referencia</strong><br>La empresa gestiona adecuadamente los aceites vegetales usados,  detergentes y otros productos que podrían ser contaminantes?<br>- ¿La empresa apoya y fomenta incentivos a las iniciativas de uso eficiente del agua, del suelo y de la biodiversidad en el cantón de Guayaquil? (Ej. A través de actividades de Responsabilidad Social Corporativa)<br>- ¿Privilegia la compra de productos nacionales que cumplan con estándares de sostenibilidad?<br>- ¿La empresa premia las buenas prácticas ambientales de sus empleados y clientes?<br>- ¿Lleva un adecuado registro (contable, bases de datos, etc.) de sus consumos (agua, energía, combustibles, insumos)?',
    'pa2_9_bool' => 'Es la aplicación de prácticas de conservación y protección del patrimonio natural, constituido por  reservas de la biósfera, los monumentos naturales, las reservas y parques nacionales, y los santuarios de la naturaleza.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa contribuye a la recuperación de ríos o quebradas en el cantón de Guayaquil? (Ej. Participa en programas de recuperación de agua, proyectos de fondos de agua, etc.)<br>- ¿La empresa cuenta con políticas o medidas para que sus actividades no dañen el patrimonio natural del cantón de Guayaquil?<br>- ¿La empresa promueve actividades de adopción o plantación de árboles para promover la conservación de los bosques?<br>- ¿La empresa apoya las acciones de protección del arbolado urbano? (Ej. Apoyo económico, acciones de voluntariado, etc.)<br>- ¿La empresa mantiene y cuida adecuadamente áreas verdes  dentro de sus instalaciones?<br>- ¿La empresa promueve el cuidado de los bosques, parques y fauna del cantón de Guayaquil? (Ej. Apoyo económico, acciones de voluntariado, etc.)',
    'pa2_10_bool' => 'Implica el desarrollo de productos y procesos que contribuyen al desarrollo sostenible, aplicando conocimientos y estrategias comerciales, además de avances  tecnológicos ecológicamente amigables, para generar mejoras ecológicas directa e indirectamente.<br><strong>Preguntas de referencia</strong><br>- ¿La empresa promueve el desarrollo de innovaciones verdes?<br>- ¿La empresa brinda incentivos a sus empleados para crear soluciones innovadoras que sean amigables con el medio ambiente?<br>- ¿La empresa cuenta con áreas o unidades específicas para llevar adelante innovaciones verdes?',
    'pa2_11_title' => 'La Huella de Carbono es un indicador de cambio climático que mide el nivel de emisiones de gases de efecto invernadero (GEI) causado directa o indirectamente por un individuo, organización, evento o producto. La gestión de esta huella implica: la medición, la aplicación de medidas de reducción y la compensación. <br><strong>Preguntas de referencia</strong><br>- ¿La empresa ha medido su Huella de Carbono?<br>- ¿La empresa cuenta con algún plan o estrategia para reducir su Huella de Carbono?<br>- ¿La empresa implementa acciones concretas para reducir la Huella de Carbono?<br>- ¿La empresa realiza alguna actividad para compensar su Huella de Carbono?',
    'pa2_12_title' => 'La Huella Hídrica es un indicador de cambio climático que mide el nivel de consumo y contaminación de los recursos de agua dulce, causado directa o indirectamente por un individuo, organización, evento o producto. La gestión de esta huella implica: la medición, la aplicación de medidas de reducción y la compensación. <br><strong>Preguntas de referencia</strong><br>- ¿La empresa ha medido su Huella Hídrica?<br>- ¿La empresa cuenta con algún plan o estrategia para reducir su Huella Hídrica?<br>- ¿La empresa implementa acciones concretas para reducir la Huella Hídrica?<br>- ¿La empresa realiza alguna actividad para compensar su Huella Hídrica?',

];
